#!/bin/zsh

# README: Script to open or focus given file with defined default opener, depending on the file extension.

# file full path, filename and extension.
file=$(fzfOpen)
echo $file
filename=${file##*\/}
extension=${filename##*\.}

# check if file param is empty
if [ -z $file ]
then
  exit
fi

# check if file param contains defined cases. 
# If yes, then do according to case.
case "$file" in
  */bin/*)
    $file &
    exit
    ;;
  *.R|*.Rmd)
    rstudio $file &
    exit
    ;;
  *.pdf)
    zathura $file &
    exit
    ;;
  *.mp3|*.mp4)
    mpv $file &
    exit
    ;;
  *.jpg|*.jpeg|*.png)
    $IMAGES $file &
    exit
    ;;
  *.py|*.hs|*.txt|*.csv|*.md)
    $TERM -e "$EDITOR $file"
    exit
    ;;
esac


# If it weren't any case,
# then check if it is a shell script.
# if yes, then either edit or launch
if [ "$extension" = "$filename" ] || [ "$extension" = "*sh" ]
then
  if [ "$1" = "launch" ]
  then
    $SHELL $file &
  elif [ "$1" = "edit" ]
  then
    $TERM -e "$EDITOR $file"
  fi
  exit
fi
